### ISSUE TITLE
Completion is not signalled after pool shutdown

### ISSUE THREAD

**Issue by oakad** [chrisvest/stormpot#100]
I'm using stormpot-2.4, currently running it under TestNG (if it's of relevance). The JVM is 1.8.0_45, but the code base is compiled for 1.7.

My shutdown sequence looks like this (timeout is set to 1000, TimeUnit.MILLISECONDS):

		Completion comp = pool.shutdown();

		try {
			for (int c = 0; c < 10; c++) {
				if (comp.await(timeout))
					return;
			}
			throw new RuntimeException(
				"Pool failed to shutdown properly"
			);
		} catch (InterruptedException e) {
			throw new RuntimeException(e);
		}

Rather frequently both BlazePool and QueuePool will fail to shutdown (comp.await() never returns true).

Does anybody know what the problem can be? There are no leaked objects, either reported by the pool or otherwise (confirmed through other means).

**Comment by chrisvest** [comment]
What other means did you use to confirm that there are no leaked objects? One way is to have an `AtomicInteger` in your allocator, that keeps track of how many objects are supposed to be in circulation. Another is to grab a heap dump. A stack dump (heap dumps include this) will tell you what the allocator thread is doing; it should be busy with a `shutPoolDown` method. The built-in leak detector only sees leaks where the objects gets garbage collected, so there is a large class of leaks that it doesn't detect. Do you get any exceptions from the pool during the test? Does Stormpot 2.3 behave in the same way?

**Comment by oakad** [comment]
I have traced all claims and releases so I can account for all objects. Moreover, it appears in debugger that allocator thread exits normally and counts down on the termination latch, yet the completion remains in non-signaled state.

I have tried with a newer JVM (_66 -  same problem); I can try with different version of stormpot as well.

I don't see any exceptions escaping from the pool or elsewhere.

**Comment by oakad** [comment]
I did some more testing and the culprit appears to be the following:

>  sun.misc.Unsafe.park(Native Method)
>  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
>  stormpot.BAllocThread.shutPoolDown(BAllocThread.java:205)
>  stormpot.BAllocThread.run(BAllocThread.java:79)
>  java.lang.Thread.run(Thread.java:745)

What appears to be beneficial for the problem is to sleep a bit (~100ms) between last object release and call to shutdown. Unfortunately, I can not rely on this in my eventual application (I'm counting on shutdown completion to wait for all objects to be released during deactivation sequence).

Thus it appears there's some sort of race in the pool shutdown code which happens when thread releases a last claimed object and then calls shutdown almost immediately.

**Comment by oakad** [comment]
It appears that the stormpot code is perfectly sound and it is my code which is to blame for occasionally swallowing an object in non-obvious fashion.

Sorry for wasting your time.
