### ISSUE TITLE
API recommendation for `Poolable`

### ISSUE THREAD

**Issue by jentfoo** [chrisvest/stormpot#104]
In the javadocs:
> A call to this method MUST delegate to a call to Slot.release(Poolable) 

This seems like a pretty important detail, and while is well documented, I was wondering if it's possible to make this simpler.  I have two potential ideas (one may not make sense, as the library is still new to me):

1) The trivial idea would be to change the `Poolable` interface from returning `void` to returning `Slot`.  This forces the implementer to recognize they don't only have to hold a reference to `Slot`, but it must be used at the point of releasing.  In addition because the `Slot` is returned, the library user should no longer need to invoke `slot.release(this);` instead the library now invoking this after release has been called.

2) This may be more from ignorance, but I don't understand why the library user needs to be concerned with the `Slot` at all?  Could this not be maintained by a class which holds an arbitrary type `<T>` reference, next to the `Slot`?  Internally you would reference this generic type, but external interfaces could store any object.

Obviously either would require a major version bump, but if interested I would be willing to submit PR's.

**Comment by chrisvest** [comment]
`Poolable.release()` is called by user code, like in http://chrisvest.github.io/stormpot/#_getting_started.

The `Slot` instance holds the pool-state for the given pooled object. User code needs to hold onto the `Slot` instance to avoid having to do a look-up on release.

**Comment by jentfoo** [comment]
Yea, I understand now, I don't think I actually have any recommendations any more.
