### ISSUE TITLE
Claim function synchronise usecase

### ISSUE THREAD

**Issue by WallEager** [chrisvest/stormpot#107]
Hey Chris

I wanted to ask how does stormpot handle synchronised issue i.e what if two threads try to claim object from the pool at a same time?

**Comment by chrisvest** [comment]
The `BlazePool` synchronises via atomic updates to the `BSlot.state` field.
The `QueuePool` relies on the thread-safety properties of the `LinkedTransferQueue` or the `LinkedBlockingQueue` from the standard Java library.

This ensures that two threads that try to claim from the pool at the same time will get different objects.
