### ISSUE TITLE
What about a kill switch Expiration?

### ISSUE THREAD

**Issue by bbottema** [chrisvest/stormpot#110]
Currently, I don't know of a way to shut down the pool instantly to support gracefully shutting down the JVM. What about a KillSwitchExpiration that can be flipped instantly expiring the entire pool?

Here's how I'm using my own implementation:
```java
public class KillSwitchExpiration<T extends Poolable> implements Expiration<T> {
	private final AtomicBoolean killSwitch;

	public KillSwitchExpiration(AtomicBoolean killSwitch) {
		this.killSwitch = killSwitch;
	}

	@Override
	public boolean hasExpired(SlotInfo<? extends T> info) {
		return killSwitch.get();
	}
}
```
Then to use it:
```java
AtomicBoolean killSwitch = new AtomicBoolean();

Config poolConfig = new Config<>()
    .setExpiration(new CompoundExpiration<>(
    	new TimeExpiration<>(1, TimeUnit.MINUTE),
	new KillSwitchExpiration<>(killSwitch)));
(..)

public void shutdownPool() {
	killSwitch.set(true);
}
```

**Comment by chrisvest** [comment]
When shut down is initiated, the pools starts to drain and deallocate their set of live objects. Unclaimed live objects are deallocated immediately. The trouble is that we have to wait for claimed objects to return to the pool. Claimed objects have already made it through their expiration check, so there's nothing more the pool can do besides waiting for all those objects to return to the pool to be deallocated.

To expedite the shut down, you need to asynchronously signal to everyone who might claim objects, to stop what they are doing, and return any claimed objects to the pool. How this mechanism is implemented, if it is even possible, is necessarily specific to the application code.

**Comment by bbottema** [comment]
Ahh I didn't realize the pool could be shut down. Your tutorial uses Pool as the declaration type, while shutdown is part of LifecycledPool.

To help newcomers, perhaps another example in the Getting Started section would be useful, including a link to the relevant Javadoc.
```java
LifecycledPool<MyPoolable> pool = new BlazePool<MyPoolable>(config);
(..)
Completion shutdownCompletion = pool.shutdown();
shutdownCompletion.await(Long.MAX_VALUE, Timeunit.DAYS); // wait forever
```

**Comment by chrisvest** [comment]
@bbottema In the main branch, those various interfaces have all been collapsed into `Pool`, so this confusion should not be a problem once that is released..

**Comment by bbottema** [comment]
That's great. Unfortunately, I'm stuck on 2.4.1 as my library needs to stick to Java 7.
