### ISSUE TITLE
Expose BlazePool.Allocator's size field

### ISSUE THREAD

**Issue by bbottema** [chrisvest/stormpot#111]
I would like to inspect the currently allocated resources, not all allocated resources ever.
```java
blazePool.getSize() // returns this.allocator.size
```
My current (ugly) workaround is using reflection, which might run into security issues making the private field accessible:
```java
int countResources() {
	try {
		return resolveField(resolveField(myBlazePool, "allocator"), "size");
	} catch (IllegalAccessException | NoSuchFieldException e) {
		throw new AssertionError("Was unable to object blazePool.allocator.size", e);
	}
}

@SuppressWarnings("unchecked")
private <T> T resolveField(Object subject, String fieldName) throws IllegalAccessException, NoSuchFieldException {
	Field fieldAllocator = subject.getClass().getDeclaredField(fieldName);
	fieldAllocator.setAccessible(true); // might be blocked by security policies
	return (T) fieldAllocator.get(subject);
}
```
Also, I can't move to 3.0.0 since I'm stuck to Java 7.

**Comment by bbottema** [comment]
I just noticed that Stormpot preemptively allocates in the background until the target size has been met. Can this be turned off so that the objects are lazily allocated (ie. when a claim comes in and size < targetSize then allocate new object)?

I'm pooling short-lived server connections and I really don't want these to be kept allocated by Stormpot, especially at times they're not needed.

**Comment by chrisvest** [comment]
A work-around would be to make your allocator update a counter that you have access to.

**Comment by bbottema** [comment]
Doing that now, but I don't like that I have to ask my Allocator for details about the pool it is allocating for. It's the wrong abstraction level. But it works for now. Gets more involved if I start implementing dynamic targetSize (#112).

**Comment by bbottema** [comment]
I switched to my own [generic-connection-pool](https://github.com/bbottema/generic-object-pool) now, so this is no longer an issue anymore (for me).
