### ISSUE TITLE
Is lazy allocation supported?

### ISSUE THREAD

**Issue by bbottema** [chrisvest/stormpot#112]
I just noticed that Stormpot preemptively allocates in the background until the target size has been met. Can this be turned off so that the objects are lazily allocated (ie. when a claim comes in and size < targetSize then allocate new object)?

I'm pooling short-lived server connections and I really don't want these to be allocated by Stormpot on the first claim, especially at times they're not needed.

**Comment by bbottema** [comment]
This is my final answer I guess:

> As it happens, the current implementations will allocate objects until the pool is full, and then stop until objects expire and needs reallocating. This effectively means that there’s no such thing as a low-water-mark in Stormpot. It also means that, if you’ve done your capacity planning right, you will have fairly predictable latencies in claiming objects from the pool, since the given size is exactly the number of objects the pool will contain at any time. On the other hand, it also means that if an object has expired, it will have to be deallocated before a replacement can be allocated.

That's really too bad, though. It makes Stormpot a little bit less of a _generic_ object pool and a little bit more of an _opinionated_ object pool. Wish it was a mater of configuration.

**Comment by chrisvest** [comment]
Yes, Stormpot optimises for low and predictable response time. However, you are allowed to change the target size at any time, so you could surround the pool with some machinery to keep track of demand and dynamically grow or shrink the pool.

**Comment by bbottema** [comment]
I working on it now, but it is very tricky.

**Comment by chrisvest** [comment]
Using `synchronized` like that will hurt performance a lot, but perhaps that's fine in your case.

I was thinking that you could perhaps use timeouts as a signal that the pool is too small. In your custom `claim` method you could initially ignore the given timeout argument and try to claim with a very small timeout. Then, if the short-timeout claim fails, you can `incrementAndGet` some atomic integer that acts as a concurrent computation vehicle for you target size, set the target size of the pool to the result of that, and try claiming again with the longer timeout.

That gives you a mechanism for increasing the target size, so now you need a way to lower it again after some time. This is harder. Whichever way you choose here, should also use the atomic integer from above to decrement and then set the target size to the result. This is actually racy, but the races "correct' themselves in that the errors don't accumulate.

One way could be use a scheduled executor service to enqueue delayed jobs that lower the target size. Another way is to have the allocator keep a counter of allocated objects, and if an object is allocated above the minimum threshold, then you can cast the `Slot` to a `SlotInfo` (kind of an ugly hack, but maybe something like this should be endorsed in the API) and use the stamp to tell a custom `Expiration` implementation that _this_ particular object is an extra, and that the target size should be lowered when it expires, and perhaps you want to expire it earlier. This strategy works best when background expiration is enabled.

Once we have a work-around that has proven itself to work well in practice, we can look at what's missing to make it easier to service this use case.

**Comment by chrisvest** [comment]
Also, the 3.0 (master) branch is tied up on missing Java 11 support in one of its dependencies (the asciidoctor javadoclet) so it won't be released any time soon, but this does not prevent me from cutting a 2.5 release if need be.

**Comment by bbottema** [comment]
> That gives you a mechanism for increasing the target size, so now you need a way to lower it again after some time. This is harder. Whichever way you choose here, should also use the atomic integer from above to decrement and then set the target size to the result.

Indeed that's what the above code was demonstrating, using an allocator that keeps track of the count using an AtomicInteger. 

Hadn't thought of the staged timeouts though. Currently I'm always assuming a bigger pool size by one is needed (assuming worst case scenario that all objects are claimed). Might try that instead.

**Comment by bbottema** [comment]
Crap, the pool has a minimum size of 1. That means I will always have a server connection open at all times.

**Comment by chrisvest** [comment]
Why is that a problem? Can you say more about your use case?

**Comment by bbottema** [comment]
Actually, I'm implementing a clustering / caching solution based on Stormpot (for the moment) to provide advanced batch support for [Simple Java Mail](https://github.com/bbottema/simple-java-mail). For advanced use cases, developers will be able to configure clusters of SMTP mail servers, each cluster backed by a collection of blaze pools.

However, I want to leave the option to the developers whether they want pre-allocated SMTP connections or not. The latter is a valid use case, because although the Stormpot cluster will initially have to start up connections, it will be able to process huge bursts of email batches very efficiently by reusing .

The on-demand lazy allocation we're discussing in this thread is currently not possible because of the imposed minimum target size of one. I'm not willing to force my users to always have a connection open though.

I currently have the following setup:

- simple-java-mail.jar (my project)
  - smtp-connection-pool.jar - smtp connection pooling and clustering (new project)
    - cluster-stormpot.jar - generic clustering / caching object pooling (new project)
       - stormpot-2.4.1.jar (your project)

**Comment by bbottema** [comment]
You can see the current state at [cluster-stormpot](https://github.com/bbottema/cluster-stormpot) (GitHub). I think it might be in working condition for my use case, but I need to do more testing first.

**Comment by bbottema** [comment]
With cluster-storm, to use it for pooling SMTP connections, this is all that is needed (you can find this micro project [here](https://github.com/simple-java-mail/smtp-connection-pool)):

```java
// these subclasses are strictly not needed, but they hide the verbose generics

public class SmtpConnectionPool extends ResourceClusters<Session, Session, SimpleDelegatingPoolable<Transport>> {
    public SmtpConnectionPool(AllocatorFactory<Session, SimpleDelegatingPoolable<Transport>> allocatorFactory, CyclingStrategy clusterStrategy, Expiration<SimpleDelegatingPoolable<Transport>> expirationPolicy, int defaultMaxPoolSize) {
        super(new SmtpClusterConfig(allocatorFactory, expirationPolicy, defaultMaxPoolSize), clusterStrategy);
    }
}

class SmtpClusterConfig extends ClusterConfig<Session, SimpleDelegatingPoolable<Transport>> {
    SmtpClusterConfig(Expiration<SimpleDelegatingPoolable<Transport>> defaultExpirationPolicy, int defaultMaxPoolSize) {
        super(new PoolableTransportAllocatorFactory(), defaultExpirationPolicy, defaultMaxPoolSize);
    }
}

class PoolableTransportAllocatorFactory implements AllocatorFactory<Session, SimpleDelegatingPoolable<Transport>> {
  public Allocator<SimpleDelegatingPoolable<Transport>> create(Session session) {
    return new PoolableTransportAllocator(session);
  }
}

class PoolableTransportAllocator implements Allocator<SimpleDelegatingPoolable<Transport>> {

  private static final Logger LOGGER = getLogger(PoolableTransportAllocator.class);

  private final Session session;

  PoolableTransportAllocator(final Session session) {
    this.session = session;
  }

  @Override
  public SimpleDelegatingPoolable<Transport> allocate(final Slot slot)
      throws NoSuchProviderException {
    LOGGER.trace("opening transport connection...");
    return new SimpleDelegatingPoolable<>(slot, session.getTransport());
  }

  @Override
  public void deallocate(final SimpleDelegatingPoolable<Transport> poolable)
      throws MessagingException {
    LOGGER.trace("closing transport...");
    poolable.getDelegate().close();
  }
}
```

**Comment by bbottema** [comment]
I just realized that not only is a minimum of 1 connections required with Stormpot, but this really also implies that it should be a long-running connection or else Stormpot just keeps allocating causing connections to be made over and over.

Typically I would like SMTP connections to last for a few seconds, handling batches/bursts of emails.

**Comment by chrisvest** [comment]
If you set the pool size to 1 and explicitly expire the slots in a pool, and then block the allocator thread on a semaphore in the allocator, immediately after deallocating the last connection, then you'll archive your goal of zero live objects, with a bonus of putting the background thread to sleep until you need it again. Pretty involved integration, though.

**Comment by bbottema** [comment]
Indeed.

**Comment by bbottema** [comment]
Forking Stormpot and allowing for 0 size fixed my issue instantly. I can now choose to maintain long-lived and short-lived allocated connections, or have them created cold when needed.

**Comment by bbottema** [comment]
I switched to my own [generic-connection-pool](https://github.com/bbottema/generic-object-pool) now, so this is no longer an issue anymore (for me).

**Comment by chrisvest** [comment]
It will be possible to set the pool size to zero, once #139 is in.
