### ISSUE TITLE
Evict poolable objects (force deallocation)?

### ISSUE THREAD

**Issue by bbottema** [chrisvest/stormpot#113]
In my SMTP connection pooling implementation, it can happen that the server connection breaks down, rendering the poolable object useless. Is there a way to evict objects from a BlazePool?

I suppose one work around is to never release such a poolable and instead increase the _targetSize_ by one. This is very hacky though. Is there a better way?

**Comment by chrisvest** [comment]
You can expire objects explicitly: http://chrisvest.github.io/stormpot/site/apidocs/stormpot/Slot.html#expire-stormpot.Poolable-

**Comment by bbottema** [comment]
Thanks, I will look into it.
