### ISSUE TITLE
Claim for newly created object first

### ISSUE THREAD

**Issue by abarazal** [chrisvest/stormpot#124]
I'm actually using Stormpot to build a socket client pool. I need to ensure that every claimed object is a Poolable that is connected to a server. So first I test the connection by sending a simple message to the server, and if it gets and exception I mark it as invalid. I repeat it until I get a valid object (conneted to the server). You can see that if there are 50 objects in the pool, I will have to test 50 times... Is there any way to get the newly allocated object instead of another object in the pool? This way I will have to test only once.

**Comment by chrisvest** [comment]
No, the newly allocated objects always to to the end of the queue. But ideally you should find a working connection before that. If you enable [background expiration checking][1], then the allocator thread will also help out with the expiration checking.

Are you saying that all 50 connections immediately become invalid at the same time?

[1]: http://chrisvest.github.io/stormpot/site/apidocs/stormpot/Config.html#setBackgroundExpirationEnabled-boolean-

**Comment by abarazal** [comment]
I thought about using background expiration check, however it not ensures that the claimed object will be valid (it may happen that streams just have been closed when claim).
Let's suppose server went down: my 50 open connections will fail when claiming. My Expiration implemetation is simple:

```java
@Slf4j
public class TestConnectionExpiration implements Expiration<PoolableSocket> {

	public boolean hasExpired(SlotInfo<? extends PoolableSocket> info) throws Exception {
		log.trace("Check if has expired...");
		PoolableSocket socket = info.getPoolable();
		if (socket.isValid()) {
			return false;
		}
		return true;
	}

}
```
socket.isValid() is a mechanism to test the connection

In my case, it will be useful to get the newly connection (newly allocated object) first so the client will have a faster response from my app.

**Comment by chrisvest** [comment]
I guess it makes sense if the live queue is operated like a stack for allocation and claiming purposes, while background expiration checking operates it like a queue. `LinkedBlockingDeque` can do that, but that would be a 3.0 change.

A work-around you can do is to add an epoch field to each PoolableSocket. Then the expiration can short-circuit and immediately expire connections that are not on the current epoch. And then you can have a circuit-breaker that increments the epoch if `socket.isValid` has returned false 3 times in a row, or something like that.

**Comment by abarazal** [comment]
Sory, I didn't undestand your work-around...
Thanks to take in consideration my use of case. I modified your code to implement a `LinkedBlockingDeque` instead a `LinkedBlockingQueue` (or any other) for live objects queue, and use `pollLast` instead of `pool`. However, it seems that first the pool has to fit its size with living objects before it returns  new object from the pool when I claim for it?

**Comment by chrisvest** [comment]
No true. The pool is populated asynchronously in a background thread, and you can started claiming objects as soon as the first ones arrive in the live queue.

**Comment by chrisvest** [comment]
Backing `claim` by a blocking stack, instead of a queue, will also improve the "idle timeout" behaviour for connection pools, as @brettwooldridge explains here: https://github.com/brettwooldridge/HikariCP/issues/931
