### ISSUE TITLE
Add Timeout constructor with a java.time.Duration parameter

### ISSUE THREAD

**Issue by PascalSchumacher** [chrisvest/stormpot#126]
As Stormpot 3 requires Java 8 it would be nice if there was a `Timeout` contructor with a `java.time.Duration` parameter.

What do you think?

By the way:
Thank you very much for providing Stormpot!

**Comment by chrisvest** [comment]
It requires Java 11. But yes, that sounds like a good idea.

**Comment by PascalSchumacher** [comment]
Thanks!
