### ISSUE TITLE
update pooled object on release

### ISSUE THREAD

**Issue by eprst** [chrisvest/stormpot#128]
I'd like to be able to return modified objects to the pool. Use case: a pool of byte buffers. Allocator creates buffers of some default size, but workers may decide to reallocate them to a bigger size, in which case I'd like to return those bigger buffers to the pool. This way we will only keep reallocating till our pool is filled with buffers of the proper size.

I'd expect this to happen when I call `Slot.release(modifiedResource)`, but as I see currently its argument is ignored.

**Comment by chrisvest** [comment]
Why not make your pooled objects mutable instead of returning different ones to the pool?

The `Slot.release` method taking the pooled object as an argument, is for sanity checking/misuse resistance purpose.

**Comment by eprst** [comment]
OK, this would add an extra layer of wrappers, but I can live with it. Thanks
