### ISSUE TITLE
Possible performance gain by switching LinkedTransferQueue to ConcurrentLinkedQueue + LockSupport

### ISSUE THREAD

**Issue by jentfoo** [chrisvest/stormpot#134]
I see that if the thread local can't be used the `LinkedTransferQueue` is deferred to.  In my experience using a `ConcurrentLinkedQueue` can get much better submission and poll throughputs.  Of course the challenge then becomes needing to yield / signal threads manually (as well as the other details like checking interrupted status).  While a burden, I expect that there is likely some performance gains to be had in switching your blocking from the synchronized wait / notify currently used in `LinkedTransferQueue`, to instead depending on `LockSupport` manually.

**Comment by chrisvest** [comment]
LinkedTransferQueue does not use monitor locks or wait/notify, though?

**Comment by jentfoo** [comment]
My mistake, this morning I was originally of LinkedBlockingQueue
