### ISSUE TITLE
Issue in BlazePool shutdown after (expire + release) on a slot for an object

### ISSUE THREAD

**Issue by chandramouli-r** [chrisvest/stormpot#135]
I'm trying to use stormpot 2.4.1 for a project and ran into an issue where in objects are not deallocated after pool shutdown. Initially, I thought it was an issue with how I'm using stormpot and that objects are being leaked in my application, but later I managed to repro it through a simple [test](https://gist.github.com/chandramouli-r/afcb69a4aec1f06c1c335f9d7f0bddf3)

Here's what I'm trying to do:
1) Maintain a map of id -> StormPot pool, where each pool has about 16 objects in steady state
2) At some point, I figure out that I need to recreate a pool for a given id, at which point I do

> BlazePool<PoolObject> p = poolMap.get(id);
Completion c = p.shutdown();
c.await(new Timeout(100, TimeUnit.MILLISECONDS));
poolMap.put(id, new BlazePool<PoolObject>(config));

3) The actual logic is a little more complicated since I can have unreleased objects at the time of pool shutdown, and I handle it in the application (the object has a reference to the pool so that I can release it to the pool).

4) In the normal (pool is not shutdown) case, I do either of the following in order to release an object back to the pool (depending on the state of the object).

> slot.release(this);
OR
slot.expire(this); slot.release(this);

The issue I'm seeing is that whenever I expire + release a claimed object, and follow it up by shutting down the pool, the released object is never de-allocated.

I reproduced the issue in a simple test by doing the following
1) create 2 pools, one BlazePool and one QueuePool
2) claim an object from each pool
3) expire+release the object back to the respective pools
4) shutdown both pools and await for 10 seconds

I observed that only the released QueuePool object is deallocated, the BlazePool object is never deallocated. Also, this issue does not show up when I replace (expire + release) with a simple (release).

Please let me know if you need any additional information.

**Comment by chandramouli-r** [comment]
Another interesting thing that I found is if I add a delay between expire+release and shutdown, it works fine. So, the following code causes the expire+released object to be deallocated (but then, the deallocation happens before shutdown is invoked). If I reduce the sleep time to 10 ms, I see the old behavior again (i.e. not deallocated).

> slot.expire(this);
slot.release(this);
Thread.sleep(100);
pool.shutdown();

**Comment by chrisvest** [comment]
Yeah, looks like there's a bug with explicit expiration and shut down. Nice find.

**Comment by chrisvest** [comment]
I no longer have access to Java 6 for doing another 2.x release, so this fix will have to be delivered as 3.x only.

**Comment by chandramouli-r** [comment]
Thanks for fixing this. Is it not possible to get a 2.4.2 release at all? We use Java 8 so moving to 3.0 will be difficult. I will be glad to help get a 2.4.2 release out since I have Java 8.

**Comment by chrisvest** [comment]
Ideally it should all be done with Java 6. I got Java 6 installed in a VM, so I'll see if the old release process can still be made to work.

**Comment by chrisvest** [comment]
Stormpot 2.4.2 has been released with this fixed.
