### ISSUE TITLE
 Inquiry About Stormpot Maintenance 🌩️

### ISSUE THREAD

**Issue by blemale** [chrisvest/stormpot#153]
Hey Chris,

Hope you're doing well! 👋 I'm a user of Stormpot and noticed the last release was about three years ago. Just wanted to check in and see if the project is still actively maintained. Any plans for future updates?

Thanks a bunch! Appreciate your work on Stormpot!

Cheers,
Bastien

**Comment by chrisvest** [comment]
Hi. Yes, I have updates planned. Getting permission to work on it is what's been taking so long, though.

**Comment by blemale** [comment]
Thanks a bunch for the quick answer!
