### ISSUE TITLE
How do I avoid the disregardPile queue from getting longer?

### ISSUE THREAD

**Issue by JiZhihan** [chrisvest/stormpot#154]
How can I prevent the disregardPile queue from growing longer over time?
After the service starts for a period of time, the length of disregardPile will increase, and the number of live objects will decrease, causing a shortage of objects in the pool. 

<img width="2047" alt="image" src="https://github.com/chrisvest/stormpot/assets/56993966/5e5c9640-e9d4-407e-9edb-0a04946845ed">

What is the reason for this, and I don't understand the significance of the disregardPile queue.

**Comment by chrisvest** [comment]
Objects in the live queue might be in the TLR_CLAIMED state. We cannot claim those. To get blocking behavior out of the queue, it must be empty. So we temporarily put the TLR_CLAIMED objects in the diregardPile. If we block on the live queue for a 100 millisecond wait quantum, without getting a useable object, then we refill the live queue with our disregarded objects and check them again. The 100 milliseconds is not tunable, unfortunately.

**Comment by JiZhihan** [comment]
Thank you for your answer
