### ISSUE TITLE
Open API classes for extension

### ISSUE THREAD

**Issue by kmila** [chrisvest/stormpot#91]
The framework classes that are directly used by the API clients, such as the default implementations of "Slot" and "SlotInfo" interfaces, should be "public final" or expose some kind of mecanism to allow extensions (ie, adding a "ForwardingSlot" delegate, allowing the client to log QAllocThread calls, or to add a retry counter, etc.)

**Comment by chrisvest** [comment]
Hi @kmila,

If I open the internal classes for extension, then I also increase the API surface and with it, the amount of testing I have to do. Plus it also restricts my ability to later change how the pool works internally.

Do you have a more specific use case we can look at instead?

**Comment by kmila** [comment]
For instance, I'd like to "lazy load" the BlazePool (call allocatorThread.start() after construction), but I can't reuse the logic as the attributes are all private protected.

Anyways, I see your point about restricting future changes, thanks for the feedback.

**Comment by chrisvest** [comment]
In the current design, the allocator thread is the only one adding objects to the pool. So delaying the start of that thread can make the first few claims slower.

You can still do it, though, if you create your own Pool implementation that wraps a lazily-created BlazePool.
