### ISSUE TITLE
Check style during build

### ISSUE THREAD

**Issue by gehel** [chrisvest/stormpot#97]
To simplify code review, basic rules that could be machine checked should be verified during Travis build.

Currently known rule is to use 2-space indent. Additional rules might be added in the future, but the first step is to ensure the checkstyle mechanism is in place.

This has been discussed in #96.

**Comment by chrisvest** [comment]
Another rule I tend to follow is an 80 column line limit. Ideally that should only produce a warning, since there might be exceptions where longer lines are more pleasing to a human eye. I guess that could go into a separate PR if produces a lot of violations that should be checked over.

**Comment by chrisvest** [comment]
Oh dang, meant to put the comment on the PR.
